### ISSUE TITLE
Checkbox Click Delay

### ISSUE THREAD

**Issue by Mahan3340** [SaeidBsn/GDCheckbox#2] opened 2017-10-28 12:50 UTC
There is a litte delay in click till it actually work , test that by clicking the checkbox fast and it wont act ( check state wont change) but sliding on it or holding it for sometime > 1s is working but pressing fast like a normal press for any touch input is not changing the checkbox state

**Comment by saeid** [comment] 2017-10-29 06:16
@Mahan3340 what version of Xcode this is happening?
Are you updating UI in the main thread? the cause of this issue is when UI update is not triggering in the main thread. let me know if this solves the issue for updating the code.

**Comment by Mahan3340** [comment] 2017-10-29 08:17
I'm suing Xcode 9 and swift 3.2 running on iPhone 6s ios 11 , I guess its on main thread cause there is not network or threading , but what should I run on MainThread ? I'm not setting anything with code but just dragged and dropped and clicking it

**Comment by saeid** [comment] 2017-10-30 17:07
@Mahan3340 I could not replicate this issue, please try to change your Swift target to 4.0 and try again. 
use for updating ui in main thread: 

>         DispatchQueue.main.async { // Code }
but basically, the checkbox update itself in main thread, just in case of test you can test this!
also try to create a test project and test there with just drag and drop the .swift file in the project and assign to a view and run the project to check if the issue is happening again or not.

**Closed as completed** 2017-11-07 15:07 UTC
